### ISSUE TITLE
issue in defining interface for nested object

### ISSUE THREAD

**Issue by suriyaJaay** [dnlrbz/angular-material#1]
I just found your awesome tutorial on angular material table..  trying to implement the same to understand the concept. but facing one issue.

Could you pls help me to understand and sort the issue in defining interface?

how can i change interface for following data structure in order to display data in table?
```

{
            name: 'xxxxx',
            description: 'xxxxx',
            obj: {
                custId: 'xxxxx-01',
                custName: 'xxxxx-dala',
                adminName: 'xxxxx',
                country: 'USA',
                region: 'Texas',                
            }
        },
```
        
when i debug, i could see data coming in dataSource in tableComponent. but its not reflecting in view. empty table only appearing. So  i modify my component's interface like below
 

```
export interface TblModel{
    /* 
    name: string;
    age: number; 
    id: number;
    description: string; 
    amount: number;
    price: number;
    discount: number;    */

    obj: Obj [];

}

export interface Obj{
    custName: string;
    custId: string;
    country: string;
    region: string;
 }
```
 
 
 but nothing works.
 
 
kindly help me on this @dnlrbz

**Comment by dnlrbz** [comment]
@suriyaJaay please fork the repository and send me the link to it, so that i can reproduce the problem

**Comment by suriyaJaay** [comment]
@dnlrbz can u pls check this [fork](https://github.com/suriyaJaay/angular-material) .. 
i have edited customer component for understanding.  Kindly look into that..

btwn.. thanks for your quick headsup mate.

**Comment by dnlrbz** [comment]
@suriyaJaay you have some inconsistency in your data model. Which interface do you want to pass to the table? This interface should not contain nested objects. And make sure the data you pass matches the interface the table accepts.

**Comment by suriyaJaay** [comment]
@dnlrbz  I believe, since it's reusable components, it supposed accept any interface structure, isn't? 

If not how make it work? 


For my customer component, I want to use, which as per my fork.. It may very component to component? 


For example, order table data structure n interface may be different.. Anyhow, the reusable component should accept any kind of interface, isn't it? 


Apologize, if am wrong. !!

**Comment by dnlrbz** [comment]
@suriyaJaay  This is a reusable component, which accepts any "flat" data objects. You have to map through your data and turn it into a flat object. If you want me to do this, please contact me on the email rabizo@me.com 

I can do it for you for 50€.

**Comment by suriyaJaay** [comment]
@dnlrbz . i wish. but am not that much rich bro... anyways i resolved that issue.  atleast can you pls help me on how to add 'edit'  'delete'& 'view' buttons like below. i just want to show those option on left side of the table..

like

```
EmpID      Name     Country            Action
----------------------------------------------------
001          AAA        UK           Edit | View | Delete
```
